server:
  port: 9090
  use-forward-headers: true
  tomcat: 
    basedir: /tmp
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
      
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: true