server:
  port: 9090
  context-path: /lol
  tomcat: 
    basedir: /tmp
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true
      
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: true